package ui

import (
	"encoding/json"
	"fmt"
	"os"
	"testing"

	"github.com/go-delve/delve/service/api"
)

func TestTransformVariables(t *testing.T) {
	var vv []api.Variable
	if err := json.Unmarshal(variablesJSON, &vv); err != nil {
		t.Fatal(err)
	}

	out := transformVariable(vv[16], nil)
	b, _ := json.MarshalIndent(out, "", "  ")
	os.Stdout.Write(b)

	fmt.Println()
}

func TestFlattenVariables(t *testing.T) {
	var vv []api.Variable
	if err := json.Unmarshal(variablesJSON, &vv); err != nil {
		t.Fatal(err)
	}

	out := transformVariables([]api.Variable{vv[13]})
	out[0].Expanded = true
	// out = flattenVariables(out)

	b, _ := json.MarshalIndent(out, "", "  ")
	os.Stdout.Write(b)
}

func TestExpandVariables(t *testing.T) {
	var vv []api.Variable
	if err := json.Unmarshal(variablesJSON, &vv); err != nil {
		t.Fatal(err)
	}
	out := transformVariables(vv)
	for i := range out {
		out[i].Expanded = true
	}

	var lines []string
	var lens []int
	expandVariables(&lines, &lens, out, 0)

	for _, line := range lines {
		fmt.Println(line)
	}
}

var variablesJSON = []byte(`[
  {
    "name": "v1",
    "addr": 1374390222888,
    "onlyAddr": false,
    "type": "int",
    "realType": "int",
    "flags": 1,
    "kind": 2,
    "value": "22",
    "len": 0,
    "cap": 0,
    "children": [],
    "base": 0,
    "unreadable": "",
    "LocationExpr": "[block] DW_OP_fbreg -0x10  (escaped)",
    "DeclLine": 17
  },
  {
    "name": "v1_",
    "addr": 1374390184616,
    "onlyAddr": false,
    "type": "string",
    "realType": "string",
    "flags": 0,
    "kind": 24,
    "value": "22",
    "len": 2,
    "cap": 0,
    "children": [],
    "base": 1374390222904,
    "unreadable": "",
    "LocationExpr": "[block] DW_OP_fbreg -0x498 ",
    "DeclLine": 18
  },
  {
    "name": "v2",
    "addr": 1374390184296,
    "onlyAddr": false,
    "type": "float64",
    "realType": "float64",
    "flags": 0,
    "kind": 14,
    "value": "7.333333333333333",
    "len": 0,
    "cap": 0,
    "children": [],
    "base": 0,
    "unreadable": "",
    "LocationExpr": "[block] DW_OP_fbreg -0x5d8 ",
    "DeclLine": 20
  },
  {
    "name": "v3",
    "addr": 1374390184600,
    "onlyAddr": false,
    "type": "string",
    "realType": "string",
    "flags": 0,
    "kind": 24,
    "value": "7.333333333333333",
    "len": 17,
    "cap": 0,
    "children": [],
    "base": 1374390239280,
    "unreadable": "",
    "LocationExpr": "[block] DW_OP_fbreg -0x4a8 ",
    "DeclLine": 21
  },
  {
    "name": "v4",
    "addr": 1374390184293,
    "onlyAddr": false,
    "type": "bool",
    "realType": "bool",
    "flags": 0,
    "kind": 1,
    "value": "false",
    "len": 0,
    "cap": 0,
    "children": [],
    "base": 0,
    "unreadable": "",
    "LocationExpr": "[block] DW_OP_fbreg -0x5db ",
    "DeclLine": 22
  },
  {
    "name": "v5",
    "addr": 1374390184576,
    "onlyAddr": false,
    "type": "[]string",
    "realType": "[]string",
    "flags": 0,
    "kind": 23,
    "value": "",
    "len": 4,
    "cap": 4,
    "children": [
      {
        "name": "",
        "addr": 1374390247488,
        "onlyAddr": false,
        "type": "string",
        "realType": "string",
        "flags": 0,
        "kind": 24,
        "value": "7.333333333333333",
        "len": 17,
        "cap": 0,
        "children": [],
        "base": 1374390239280,
        "unreadable": "",
        "LocationExpr": "",
        "DeclLine": 0
      },
      {
        "name": "",
        "addr": 1374390247504,
        "onlyAddr": false,
        "type": "string",
        "realType": "string",
        "flags": 0,
        "kind": 24,
        "value": "hellO",
        "len": 5,
        "cap": 0,
        "children": [],
        "base": 4302799450,
        "unreadable": "",
        "LocationExpr": "",
        "DeclLine": 0
      },
      {
        "name": "",
        "addr": 1374390247520,
        "onlyAddr": false,
        "type": "string",
        "realType": "string",
        "flags": 0,
        "kind": 24,
        "value": "7.333333333333333",
        "len": 17,
        "cap": 0,
        "children": [],
        "base": 1374390239280,
        "unreadable": "",
        "LocationExpr": "",
        "DeclLine": 0
      },
      {
        "name": "",
        "addr": 1374390247536,
        "onlyAddr": false,
        "type": "string",
        "realType": "string",
        "flags": 0,
        "kind": 24,
        "value": "22",
        "len": 2,
        "cap": 0,
        "children": [],
        "base": 1374390222904,
        "unreadable": "",
        "LocationExpr": "",
        "DeclLine": 0
      }
    ],
    "base": 1374390247488,
    "unreadable": "",
    "LocationExpr": "[block] DW_OP_fbreg -0x4c0 ",
    "DeclLine": 23
  },
  {
    "name": "v6",
    "addr": 1374390184552,
    "onlyAddr": false,
    "type": "[]interface {}",
    "realType": "[]interface {}",
    "flags": 0,
    "kind": 23,
    "value": "",
    "len": 2,
    "cap": 2,
    "children": [
      {
        "name": "",
        "addr": 1374390132768,
        "onlyAddr": false,
        "type": "interface {}",
        "realType": "interface {}",
        "flags": 0,
        "kind": 20,
        "value": "",
        "len": 0,
        "cap": 0,
        "children": [
          {
            "name": "data",
            "addr": 4303095192,
            "onlyAddr": false,
            "type": "string",
            "realType": "string",
            "flags": 0,
            "kind": 24,
            "value": "foo",
            "len": 3,
            "cap": 0,
            "children": [],
            "base": 4302799119,
            "unreadable": "",
            "LocationExpr": "",
            "DeclLine": 0
          }
        ],
        "base": 0,
        "unreadable": "",
        "LocationExpr": "",
        "DeclLine": 0
      },
      {
        "name": "",
        "addr": 1374390132784,
        "onlyAddr": false,
        "type": "interface {}",
        "realType": "interface {}",
        "flags": 0,
        "kind": 20,
        "value": "",
        "len": 0,
        "cap": 0,
        "children": [
          {
            "name": "data",
            "addr": 4303095208,
            "onlyAddr": false,
            "type": "string",
            "realType": "string",
            "flags": 0,
            "kind": 24,
            "value": "bar",
            "len": 3,
            "cap": 0,
            "children": [],
            "base": 4302799122,
            "unreadable": "",
            "LocationExpr": "",
            "DeclLine": 0
          }
        ],
        "base": 0,
        "unreadable": "",
        "LocationExpr": "",
        "DeclLine": 0
      }
    ],
    "base": 1374390132768,
    "unreadable": "",
    "LocationExpr": "[block] DW_OP_fbreg -0x4d8 ",
    "DeclLine": 24
  },
  {
    "name": "v7",
    "addr": 1374390184528,
    "onlyAddr": false,
    "type": "[][]string",
    "realType": "[][]string",
    "flags": 0,
    "kind": 23,
    "value": "",
    "len": 1,
    "cap": 1,
    "children": [
      {
        "name": "",
        "addr": 1374390312960,
        "onlyAddr": false,
        "type": "[]string",
        "realType": "[]string",
        "flags": 0,
        "kind": 23,
        "value": "",
        "len": 2,
        "cap": 2,
        "children": [
          {
            "name": "",
            "addr": 1374390132800,
            "onlyAddr": false,
            "type": "string",
            "realType": "string",
            "flags": 0,
            "kind": 24,
            "value": "foo",
            "len": 3,
            "cap": 0,
            "children": [],
            "base": 4302799119,
            "unreadable": "",
            "LocationExpr": "",
            "DeclLine": 0
          },
          {
            "name": "",
            "addr": 1374390132816,
            "onlyAddr": false,
            "type": "string",
            "realType": "string",
            "flags": 0,
            "kind": 24,
            "value": "bar",
            "len": 3,
            "cap": 0,
            "children": [],
            "base": 4302799122,
            "unreadable": "",
            "LocationExpr": "",
            "DeclLine": 0
          }
        ],
        "base": 1374390132800,
        "unreadable": "",
        "LocationExpr": "",
        "DeclLine": 0
      }
    ],
    "base": 1374390312960,
    "unreadable": "",
    "LocationExpr": "[block] DW_OP_fbreg -0x4f0 ",
    "DeclLine": 25
  },
  {
    "name": "v8",
    "addr": 1374390184504,
    "onlyAddr": false,
    "type": "struct { main.data []string }",
    "realType": "struct { main.data []string }",
    "flags": 0,
    "kind": 25,
    "value": "",
    "len": 1,
    "cap": 0,
    "children": [
      {
        "name": "data",
        "addr": 1374390184504,
        "onlyAddr": false,
        "type": "[]string",
        "realType": "[]string",
        "flags": 0,
        "kind": 23,
        "value": "",
        "len": 1,
        "cap": 1,
        "children": [
          {
            "name": "",
            "addr": 1374390124656,
            "onlyAddr": false,
            "type": "string",
            "realType": "string",
            "flags": 0,
            "kind": 24,
            "value": "foo",
            "len": 3,
            "cap": 0,
            "children": [],
            "base": 4302799119,
            "unreadable": "",
            "LocationExpr": "",
            "DeclLine": 0
          }
        ],
        "base": 1374390124656,
        "unreadable": "",
        "LocationExpr": "",
        "DeclLine": 0
      }
    ],
    "base": 0,
    "unreadable": "",
    "LocationExpr": "[block] DW_OP_fbreg -0x508 ",
    "DeclLine": 26
  },
  {
    "name": "v9",
    "addr": 1374390184456,
    "onlyAddr": false,
    "type": "main.Foo",
    "realType": "main.Foo",
    "flags": 0,
    "kind": 25,
    "value": "",
    "len": 3,
    "cap": 0,
    "children": [
      {
        "name": "Data",
        "addr": 1374390184456,
        "onlyAddr": false,
        "type": "[]string",
        "realType": "[]string",
        "flags": 0,
        "kind": 23,
        "value": "",
        "len": 1,
        "cap": 1,
        "children": [
          {
            "name": "",
            "addr": 1374390124672,
            "onlyAddr": false,
            "type": "string",
            "realType": "string",
            "flags": 0,
            "kind": 24,
            "value": "foo",
            "len": 3,
            "cap": 0,
            "children": [],
            "base": 4302799119,
            "unreadable": "",
            "LocationExpr": "",
            "DeclLine": 0
          }
        ],
        "base": 1374390124672,
        "unreadable": "",
        "LocationExpr": "",
        "DeclLine": 0
      },
      {
        "name": "Lol",
        "addr": 1374390184480,
        "onlyAddr": false,
        "type": "string",
        "realType": "string",
        "flags": 0,
        "kind": 24,
        "value": "Helloworld",
        "len": 10,
        "cap": 0,
        "children": [],
        "base": 4302801597,
        "unreadable": "",
        "LocationExpr": "",
        "DeclLine": 0
      },
      {
        "name": "Hello",
        "addr": 1374390184496,
        "onlyAddr": false,
        "type": "int",
        "realType": "int",
        "flags": 0,
        "kind": 2,
        "value": "10",
        "len": 0,
        "cap": 0,
        "children": [],
        "base": 0,
        "unreadable": "",
        "LocationExpr": "",
        "DeclLine": 0
      }
    ],
    "base": 0,
    "unreadable": "",
    "LocationExpr": "[block] DW_OP_fbreg -0x538 ",
    "DeclLine": 27
  },
  {
    "name": "v10",
    "addr": 1374390184304,
    "onlyAddr": false,
    "type": "[10]int",
    "realType": "[10]int",
    "flags": 0,
    "kind": 17,
    "value": "",
    "len": 10,
    "cap": 10,
    "children": [
      {
        "name": "",
        "addr": 1374390184304,
        "onlyAddr": false,
        "type": "int",
        "realType": "int",
        "flags": 0,
        "kind": 2,
        "value": "0",
        "len": 0,
        "cap": 0,
        "children": [],
        "base": 0,
        "unreadable": "",
        "LocationExpr": "",
        "DeclLine": 0
      },
      {
        "name": "",
        "addr": 1374390184312,
        "onlyAddr": false,
        "type": "int",
        "realType": "int",
        "flags": 0,
        "kind": 2,
        "value": "0",
        "len": 0,
        "cap": 0,
        "children": [],
        "base": 0,
        "unreadable": "",
        "LocationExpr": "",
        "DeclLine": 0
      },
      {
        "name": "",
        "addr": 1374390184320,
        "onlyAddr": false,
        "type": "int",
        "realType": "int",
        "flags": 0,
        "kind": 2,
        "value": "0",
        "len": 0,
        "cap": 0,
        "children": [],
        "base": 0,
        "unreadable": "",
        "LocationExpr": "",
        "DeclLine": 0
      },
      {
        "name": "",
        "addr": 1374390184328,
        "onlyAddr": false,
        "type": "int",
        "realType": "int",
        "flags": 0,
        "kind": 2,
        "value": "0",
        "len": 0,
        "cap": 0,
        "children": [],
        "base": 0,
        "unreadable": "",
        "LocationExpr": "",
        "DeclLine": 0
      },
      {
        "name": "",
        "addr": 1374390184336,
        "onlyAddr": false,
        "type": "int",
        "realType": "int",
        "flags": 0,
        "kind": 2,
        "value": "0",
        "len": 0,
        "cap": 0,
        "children": [],
        "base": 0,
        "unreadable": "",
        "LocationExpr": "",
        "DeclLine": 0
      },
      {
        "name": "",
        "addr": 1374390184344,
        "onlyAddr": false,
        "type": "int",
        "realType": "int",
        "flags": 0,
        "kind": 2,
        "value": "0",
        "len": 0,
        "cap": 0,
        "children": [],
        "base": 0,
        "unreadable": "",
        "LocationExpr": "",
        "DeclLine": 0
      },
      {
        "name": "",
        "addr": 1374390184352,
        "onlyAddr": false,
        "type": "int",
        "realType": "int",
        "flags": 0,
        "kind": 2,
        "value": "0",
        "len": 0,
        "cap": 0,
        "children": [],
        "base": 0,
        "unreadable": "",
        "LocationExpr": "",
        "DeclLine": 0
      },
      {
        "name": "",
        "addr": 1374390184360,
        "onlyAddr": false,
        "type": "int",
        "realType": "int",
        "flags": 0,
        "kind": 2,
        "value": "0",
        "len": 0,
        "cap": 0,
        "children": [],
        "base": 0,
        "unreadable": "",
        "LocationExpr": "",
        "DeclLine": 0
      },
      {
        "name": "",
        "addr": 1374390184368,
        "onlyAddr": false,
        "type": "int",
        "realType": "int",
        "flags": 0,
        "kind": 2,
        "value": "0",
        "len": 0,
        "cap": 0,
        "children": [],
        "base": 0,
        "unreadable": "",
        "LocationExpr": "",
        "DeclLine": 0
      },
      {
        "name": "",
        "addr": 1374390184376,
        "onlyAddr": false,
        "type": "int",
        "realType": "int",
        "flags": 0,
        "kind": 2,
        "value": "0",
        "len": 0,
        "cap": 0,
        "children": [],
        "base": 0,
        "unreadable": "",
        "LocationExpr": "",
        "DeclLine": 0
      }
    ],
    "base": 1374390184304,
    "unreadable": "",
    "LocationExpr": "[block] DW_OP_fbreg -0x5d0 ",
    "DeclLine": 28
  },
  {
    "name": "v11",
    "addr": 1374390184664,
    "onlyAddr": false,
    "type": "func(string, string, string)",
    "realType": "func(string, string, string)",
    "flags": 0,
    "kind": 19,
    "value": "main.main.func1",
    "len": 0,
    "cap": 0,
    "children": [],
    "base": 4302798240,
    "unreadable": "",
    "LocationExpr": "[block] DW_OP_fbreg -0x468 ",
    "DeclLine": 29
  },
  {
    "name": "v12",
    "addr": 1374390184656,
    "onlyAddr": false,
    "type": "map[string]interface {}",
    "realType": "map[string]interface {}",
    "flags": 0,
    "kind": 21,
    "value": "",
    "len": 3,
    "cap": 0,
    "children": [
      {
        "name": "",
        "addr": 1374390321160,
        "onlyAddr": false,
        "type": "string",
        "realType": "string",
        "flags": 0,
        "kind": 24,
        "value": "foo",
        "len": 3,
        "cap": 0,
        "children": [],
        "base": 4302799119,
        "unreadable": "",
        "LocationExpr": "",
        "DeclLine": 0
      },
      {
        "name": "",
        "addr": 1374390321288,
        "onlyAddr": false,
        "type": "interface {}",
        "realType": "interface {}",
        "flags": 0,
        "kind": 20,
        "value": "",
        "len": 0,
        "cap": 0,
        "children": [
          {
            "name": "data",
            "addr": 4302947088,
            "onlyAddr": false,
            "type": "int",
            "realType": "int",
            "flags": 0,
            "kind": 2,
            "value": "10",
            "len": 0,
            "cap": 0,
            "children": [],
            "base": 0,
            "unreadable": "",
            "LocationExpr": "",
            "DeclLine": 0
          }
        ],
        "base": 0,
        "unreadable": "",
        "LocationExpr": "",
        "DeclLine": 0
      },
      {
        "name": "",
        "addr": 1374390321176,
        "onlyAddr": false,
        "type": "string",
        "realType": "string",
        "flags": 0,
        "kind": 24,
        "value": "bar",
        "len": 3,
        "cap": 0,
        "children": [],
        "base": 4302799122,
        "unreadable": "",
        "LocationExpr": "",
        "DeclLine": 0
      },
      {
        "name": "",
        "addr": 1374390321304,
        "onlyAddr": false,
        "type": "interface {}",
        "realType": "interface {}",
        "flags": 0,
        "kind": 20,
        "value": "",
        "len": 0,
        "cap": 0,
        "children": [
          {
            "name": "data",
            "addr": 1374390312984,
            "onlyAddr": false,
            "type": "[]string",
            "realType": "[]string",
            "flags": 0,
            "kind": 23,
            "value": "",
            "len": 1,
            "cap": 1,
            "children": [
              {
                "name": "",
                "addr": 1374390124688,
                "onlyAddr": false,
                "type": "string",
                "realType": "string",
                "flags": 0,
                "kind": 24,
                "value": "hello",
                "len": 5,
                "cap": 0,
                "children": [],
                "base": 4302799455,
                "unreadable": "",
                "LocationExpr": "",
                "DeclLine": 0
              }
            ],
            "base": 1374390124688,
            "unreadable": "",
            "LocationExpr": "",
            "DeclLine": 0
          }
        ],
        "base": 0,
        "unreadable": "",
        "LocationExpr": "",
        "DeclLine": 0
      },
      {
        "name": "",
        "addr": 1374390321192,
        "onlyAddr": false,
        "type": "string",
        "realType": "string",
        "flags": 0,
        "kind": 24,
        "value": "baz",
        "len": 3,
        "cap": 0,
        "children": [],
        "base": 4302799125,
        "unreadable": "",
        "LocationExpr": "",
        "DeclLine": 0
      },
      {
        "name": "",
        "addr": 1374390321320,
        "onlyAddr": false,
        "type": "interface {}",
        "realType": "interface {}",
        "flags": 0,
        "kind": 20,
        "value": "",
        "len": 0,
        "cap": 0,
        "children": [
          {
            "name": "data",
            "addr": 1374390321328,
            "onlyAddr": false,
            "type": "map[string]int",
            "realType": "map[string]int",
            "flags": 0,
            "kind": 21,
            "value": "",
            "len": 1,
            "cap": 0,
            "children": [
              {
                "name": "",
                "addr": 1374390257288,
                "onlyAddr": false,
                "type": "string",
                "realType": "string",
                "flags": 0,
                "kind": 24,
                "value": "a",
                "len": 1,
                "cap": 0,
                "children": [],
                "base": 4302799040,
                "unreadable": "",
                "LocationExpr": "",
                "DeclLine": 0
              },
              {
                "name": "",
                "addr": 1374390257416,
                "onlyAddr": false,
                "type": "int",
                "realType": "int",
                "flags": 0,
                "kind": 2,
                "value": "1",
                "len": 0,
                "cap": 0,
                "children": [],
                "base": 0,
                "unreadable": "",
                "LocationExpr": "",
                "DeclLine": 0
              }
            ],
            "base": 1374390215040,
            "unreadable": "",
            "LocationExpr": "",
            "DeclLine": 0
          }
        ],
        "base": 0,
        "unreadable": "",
        "LocationExpr": "",
        "DeclLine": 0
      }
    ],
    "base": 1374390214992,
    "unreadable": "",
    "LocationExpr": "[block] DW_OP_fbreg -0x470 ",
    "DeclLine": 30
  },
  {
    "name": "v13",
    "addr": 1374390184648,
    "onlyAddr": false,
    "type": "chan int",
    "realType": "chan int",
    "flags": 0,
    "kind": 18,
    "value": "",
    "len": 11,
    "cap": 0,
    "children": [
      {
        "name": "qcount",
        "addr": 1374390329344,
        "onlyAddr": false,
        "type": "uint",
        "realType": "uint",
        "flags": 0,
        "kind": 7,
        "value": "1",
        "len": 0,
        "cap": 0,
        "children": [],
        "base": 0,
        "unreadable": "",
        "LocationExpr": "",
        "DeclLine": 0
      },
      {
        "name": "dataqsiz",
        "addr": 1374390329352,
        "onlyAddr": false,
        "type": "uint",
        "realType": "uint",
        "flags": 0,
        "kind": 7,
        "value": "10",
        "len": 0,
        "cap": 0,
        "children": [],
        "base": 0,
        "unreadable": "",
        "LocationExpr": "",
        "DeclLine": 0
      },
      {
        "name": "buf",
        "addr": 1374390329360,
        "onlyAddr": false,
        "type": "*[10]int",
        "realType": "*[10]int",
        "flags": 0,
        "kind": 22,
        "value": "1374390329440",
        "len": 1,
        "cap": 0,
        "children": [
          {
            "name": "",
            "addr": 1374390329440,
            "onlyAddr": false,
            "type": "[10]int",
            "realType": "[10]int",
            "flags": 0,
            "kind": 17,
            "value": "",
            "len": 10,
            "cap": 10,
            "children": [
              {
                "name": "",
                "addr": 1374390329440,
                "onlyAddr": false,
                "type": "int",
                "realType": "int",
                "flags": 0,
                "kind": 2,
                "value": "0",
                "len": 0,
                "cap": 0,
                "children": [],
                "base": 0,
                "unreadable": "",
                "LocationExpr": "",
                "DeclLine": 0
              },
              {
                "name": "",
                "addr": 1374390329448,
                "onlyAddr": false,
                "type": "int",
                "realType": "int",
                "flags": 0,
                "kind": 2,
                "value": "0",
                "len": 0,
                "cap": 0,
                "children": [],
                "base": 0,
                "unreadable": "",
                "LocationExpr": "",
                "DeclLine": 0
              },
              {
                "name": "",
                "addr": 1374390329456,
                "onlyAddr": false,
                "type": "int",
                "realType": "int",
                "flags": 0,
                "kind": 2,
                "value": "3",
                "len": 0,
                "cap": 0,
                "children": [],
                "base": 0,
                "unreadable": "",
                "LocationExpr": "",
                "DeclLine": 0
              },
              {
                "name": "",
                "addr": 1374390329464,
                "onlyAddr": false,
                "type": "int",
                "realType": "int",
                "flags": 0,
                "kind": 2,
                "value": "0",
                "len": 0,
                "cap": 0,
                "children": [],
                "base": 0,
                "unreadable": "",
                "LocationExpr": "",
                "DeclLine": 0
              },
              {
                "name": "",
                "addr": 1374390329472,
                "onlyAddr": false,
                "type": "int",
                "realType": "int",
                "flags": 0,
                "kind": 2,
                "value": "0",
                "len": 0,
                "cap": 0,
                "children": [],
                "base": 0,
                "unreadable": "",
                "LocationExpr": "",
                "DeclLine": 0
              },
              {
                "name": "",
                "addr": 1374390329480,
                "onlyAddr": false,
                "type": "int",
                "realType": "int",
                "flags": 0,
                "kind": 2,
                "value": "0",
                "len": 0,
                "cap": 0,
                "children": [],
                "base": 0,
                "unreadable": "",
                "LocationExpr": "",
                "DeclLine": 0
              },
              {
                "name": "",
                "addr": 1374390329488,
                "onlyAddr": false,
                "type": "int",
                "realType": "int",
                "flags": 0,
                "kind": 2,
                "value": "0",
                "len": 0,
                "cap": 0,
                "children": [],
                "base": 0,
                "unreadable": "",
                "LocationExpr": "",
                "DeclLine": 0
              },
              {
                "name": "",
                "addr": 1374390329496,
                "onlyAddr": false,
                "type": "int",
                "realType": "int",
                "flags": 0,
                "kind": 2,
                "value": "0",
                "len": 0,
                "cap": 0,
                "children": [],
                "base": 0,
                "unreadable": "",
                "LocationExpr": "",
                "DeclLine": 0
              },
              {
                "name": "",
                "addr": 1374390329504,
                "onlyAddr": false,
                "type": "int",
                "realType": "int",
                "flags": 0,
                "kind": 2,
                "value": "0",
                "len": 0,
                "cap": 0,
                "children": [],
                "base": 0,
                "unreadable": "",
                "LocationExpr": "",
                "DeclLine": 0
              },
              {
                "name": "",
                "addr": 1374390329512,
                "onlyAddr": false,
                "type": "int",
                "realType": "int",
                "flags": 0,
                "kind": 2,
                "value": "0",
                "len": 0,
                "cap": 0,
                "children": [],
                "base": 0,
                "unreadable": "",
                "LocationExpr": "",
                "DeclLine": 0
              }
            ],
            "base": 1374390329440,
            "unreadable": "",
            "LocationExpr": "",
            "DeclLine": 0
          }
        ],
        "base": 0,
        "unreadable": "",
        "LocationExpr": "",
        "DeclLine": 0
      },
      {
        "name": "elemsize",
        "addr": 1374390329368,
        "onlyAddr": false,
        "type": "uint16",
        "realType": "uint16",
        "flags": 0,
        "kind": 7,
        "value": "8",
        "len": 0,
        "cap": 0,
        "children": [],
        "base": 0,
        "unreadable": "",
        "LocationExpr": "",
        "DeclLine": 0
      },
      {
        "name": "closed",
        "addr": 1374390329372,
        "onlyAddr": false,
        "type": "uint32",
        "realType": "uint32",
        "flags": 0,
        "kind": 7,
        "value": "0",
        "len": 0,
        "cap": 0,
        "children": [],
        "base": 0,
        "unreadable": "",
        "LocationExpr": "",
        "DeclLine": 0
      },
      {
        "name": "elemtype",
        "addr": 1374390329376,
        "onlyAddr": false,
        "type": "*internal/abi.Type",
        "realType": "*internal/abi.Type",
        "flags": 0,
        "kind": 22,
        "value": "4302998880",
        "len": 1,
        "cap": 0,
        "children": [
          {
            "name": "",
            "addr": 4302998880,
            "onlyAddr": false,
            "type": "internal/abi.Type",
            "realType": "internal/abi.Type",
            "flags": 0,
            "kind": 25,
            "value": "",
            "len": 11,
            "cap": 0,
            "children": [
              {
                "name": "Size_",
                "addr": 4302998880,
                "onlyAddr": false,
                "type": "uintptr",
                "realType": "uintptr",
                "flags": 0,
                "kind": 7,
                "value": "8",
                "len": 0,
                "cap": 0,
                "children": [],
                "base": 0,
                "unreadable": "",
                "LocationExpr": "",
                "DeclLine": 0
              },
              {
                "name": "PtrBytes",
                "addr": 4302998888,
                "onlyAddr": false,
                "type": "uintptr",
                "realType": "uintptr",
                "flags": 0,
                "kind": 7,
                "value": "0",
                "len": 0,
                "cap": 0,
                "children": [],
                "base": 0,
                "unreadable": "",
                "LocationExpr": "",
                "DeclLine": 0
              },
              {
                "name": "Hash",
                "addr": 4302998896,
                "onlyAddr": false,
                "type": "uint32",
                "realType": "uint32",
                "flags": 0,
                "kind": 7,
                "value": "3413333906",
                "len": 0,
                "cap": 0,
                "children": [],
                "base": 0,
                "unreadable": "",
                "LocationExpr": "",
                "DeclLine": 0
              },
              {
                "name": "TFlag",
                "addr": 4302998900,
                "onlyAddr": false,
                "type": "internal/abi.TFlag",
                "realType": "internal/abi.TFlag",
                "flags": 0,
                "kind": 7,
                "value": "TFlagUncommon|TFlagExtraStar|TFlagNamed|TFlagRegularMemory (15)",
                "len": 0,
                "cap": 0,
                "children": [],
                "base": 0,
                "unreadable": "",
                "LocationExpr": "",
                "DeclLine": 0
              },
              {
                "name": "Align_",
                "addr": 4302998901,
                "onlyAddr": false,
                "type": "uint8",
                "realType": "uint8",
                "flags": 0,
                "kind": 7,
                "value": "8",
                "len": 0,
                "cap": 0,
                "children": [],
                "base": 0,
                "unreadable": "",
                "LocationExpr": "",
                "DeclLine": 0
              },
              {
                "name": "FieldAlign_",
                "addr": 4302998902,
                "onlyAddr": false,
                "type": "uint8",
                "realType": "uint8",
                "flags": 0,
                "kind": 7,
                "value": "8",
                "len": 0,
                "cap": 0,
                "children": [],
                "base": 0,
                "unreadable": "",
                "LocationExpr": "",
                "DeclLine": 0
              },
              {
                "name": "Kind_",
                "addr": 4302998903,
                "onlyAddr": false,
                "type": "uint8",
                "realType": "uint8",
                "flags": 0,
                "kind": 7,
                "value": "2",
                "len": 0,
                "cap": 0,
                "children": [],
                "base": 0,
                "unreadable": "",
                "LocationExpr": "",
                "DeclLine": 0
              },
              {
                "name": "Equal",
                "addr": 4302998904,
                "onlyAddr": false,
                "type": "func(unsafe.Pointer, unsafe.Pointer) bool",
                "realType": "func(unsafe.Pointer, unsafe.Pointer) bool",
                "flags": 0,
                "kind": 19,
                "value": "runtime.memequal64",
                "len": 0,
                "cap": 0,
                "children": [],
                "base": 4302192400,
                "unreadable": "",
                "LocationExpr": "",
                "DeclLine": 0
              },
              {
                "name": "GCData",
                "addr": 4302998912,
                "onlyAddr": false,
                "type": "*uint8",
                "realType": "*uint8",
                "flags": 0,
                "kind": 22,
                "value": "4302947076",
                "len": 1,
                "cap": 0,
                "children": [
                  {
                    "name": "",
                    "addr": 4302947076,
                    "onlyAddr": false,
                    "type": "uint8",
                    "realType": "uint8",
                    "flags": 0,
                    "kind": 7,
                    "value": "0",
                    "len": 0,
                    "cap": 0,
                    "children": [],
                    "base": 0,
                    "unreadable": "",
                    "LocationExpr": "",
                    "DeclLine": 0
                  }
                ],
                "base": 0,
                "unreadable": "",
                "LocationExpr": "",
                "DeclLine": 0
              },
              {
                "name": "Str",
                "addr": 4302998920,
                "onlyAddr": false,
                "type": "internal/abi.NameOff",
                "realType": "internal/abi.NameOff",
                "flags": 0,
                "kind": 2,
                "value": "1155",
                "len": 0,
                "cap": 0,
                "children": [],
                "base": 0,
                "unreadable": "",
                "LocationExpr": "",
                "DeclLine": 0
              },
              {
                "name": "PtrToThis",
                "addr": 4302998924,
                "onlyAddr": false,
                "type": "internal/abi.TypeOff",
                "realType": "internal/abi.TypeOff",
                "flags": 0,
                "kind": 2,
                "value": "25952",
                "len": 0,
                "cap": 0,
                "children": [],
                "base": 0,
                "unreadable": "",
                "LocationExpr": "",
                "DeclLine": 0
              }
            ],
            "base": 0,
            "unreadable": "",
            "LocationExpr": "",
            "DeclLine": 0
          }
        ],
        "base": 0,
        "unreadable": "",
        "LocationExpr": "",
        "DeclLine": 0
      },
      {
        "name": "sendx",
        "addr": 1374390329384,
        "onlyAddr": false,
        "type": "uint",
        "realType": "uint",
        "flags": 0,
        "kind": 7,
        "value": "3",
        "len": 0,
        "cap": 0,
        "children": [],
        "base": 0,
        "unreadable": "",
        "LocationExpr": "",
        "DeclLine": 0
      },
      {
        "name": "recvx",
        "addr": 1374390329392,
        "onlyAddr": false,
        "type": "uint",
        "realType": "uint",
        "flags": 0,
        "kind": 7,
        "value": "2",
        "len": 0,
        "cap": 0,
        "children": [],
        "base": 0,
        "unreadable": "",
        "LocationExpr": "",
        "DeclLine": 0
      },
      {
        "name": "recvq",
        "addr": 1374390329400,
        "onlyAddr": false,
        "type": "waitq\u003cint\u003e",
        "realType": "waitq\u003cint\u003e",
        "flags": 0,
        "kind": 25,
        "value": "",
        "len": 2,
        "cap": 0,
        "children": [
          {
            "name": "first",
            "addr": 1374390329400,
            "onlyAddr": false,
            "type": "*sudog\u003cint\u003e",
            "realType": "*sudog\u003cint\u003e",
            "flags": 0,
            "kind": 22,
            "value": "0",
            "len": 1,
            "cap": 0,
            "children": [
              {
                "name": "",
                "addr": 0,
                "onlyAddr": false,
                "type": "sudog\u003cint\u003e",
                "realType": "sudog\u003cint\u003e",
                "flags": 0,
                "kind": 25,
                "value": "",
                "len": 0,
                "cap": 0,
                "children": [],
                "base": 0,
                "unreadable": "",
                "LocationExpr": "",
                "DeclLine": 0
              }
            ],
            "base": 0,
            "unreadable": "",
            "LocationExpr": "",
            "DeclLine": 0
          },
          {
            "name": "last",
            "addr": 1374390329408,
            "onlyAddr": false,
            "type": "*sudog\u003cint\u003e",
            "realType": "*sudog\u003cint\u003e",
            "flags": 0,
            "kind": 22,
            "value": "0",
            "len": 1,
            "cap": 0,
            "children": [
              {
                "name": "",
                "addr": 0,
                "onlyAddr": false,
                "type": "sudog\u003cint\u003e",
                "realType": "sudog\u003cint\u003e",
                "flags": 0,
                "kind": 25,
                "value": "",
                "len": 0,
                "cap": 0,
                "children": [],
                "base": 0,
                "unreadable": "",
                "LocationExpr": "",
                "DeclLine": 0
              }
            ],
            "base": 0,
            "unreadable": "",
            "LocationExpr": "",
            "DeclLine": 0
          }
        ],
        "base": 0,
        "unreadable": "",
        "LocationExpr": "",
        "DeclLine": 0
      },
      {
        "name": "sendq",
        "addr": 1374390329416,
        "onlyAddr": false,
        "type": "waitq\u003cint\u003e",
        "realType": "waitq\u003cint\u003e",
        "flags": 0,
        "kind": 25,
        "value": "",
        "len": 2,
        "cap": 0,
        "children": [
          {
            "name": "first",
            "addr": 1374390329416,
            "onlyAddr": false,
            "type": "*sudog\u003cint\u003e",
            "realType": "*sudog\u003cint\u003e",
            "flags": 0,
            "kind": 22,
            "value": "0",
            "len": 1,
            "cap": 0,
            "children": [
              {
                "name": "",
                "addr": 0,
                "onlyAddr": false,
                "type": "sudog\u003cint\u003e",
                "realType": "sudog\u003cint\u003e",
                "flags": 0,
                "kind": 25,
                "value": "",
                "len": 0,
                "cap": 0,
                "children": [],
                "base": 0,
                "unreadable": "",
                "LocationExpr": "",
                "DeclLine": 0
              }
            ],
            "base": 0,
            "unreadable": "",
            "LocationExpr": "",
            "DeclLine": 0
          },
          {
            "name": "last",
            "addr": 1374390329424,
            "onlyAddr": false,
            "type": "*sudog\u003cint\u003e",
            "realType": "*sudog\u003cint\u003e",
            "flags": 0,
            "kind": 22,
            "value": "0",
            "len": 1,
            "cap": 0,
            "children": [
              {
                "name": "",
                "addr": 0,
                "onlyAddr": false,
                "type": "sudog\u003cint\u003e",
                "realType": "sudog\u003cint\u003e",
                "flags": 0,
                "kind": 25,
                "value": "",
                "len": 0,
                "cap": 0,
                "children": [],
                "base": 0,
                "unreadable": "",
                "LocationExpr": "",
                "DeclLine": 0
              }
            ],
            "base": 0,
            "unreadable": "",
            "LocationExpr": "",
            "DeclLine": 0
          }
        ],
        "base": 0,
        "unreadable": "",
        "LocationExpr": "",
        "DeclLine": 0
      },
      {
        "name": "lock",
        "addr": 1374390329432,
        "onlyAddr": false,
        "type": "runtime.mutex",
        "realType": "runtime.mutex",
        "flags": 0,
        "kind": 25,
        "value": "",
        "len": 2,
        "cap": 0,
        "children": [
          {
            "name": "lockRankStruct",
            "addr": 1374390329432,
            "onlyAddr": false,
            "type": "runtime.lockRankStruct",
            "realType": "runtime.lockRankStruct",
            "flags": 0,
            "kind": 25,
            "value": "",
            "len": 0,
            "cap": 0,
            "children": [],
            "base": 0,
            "unreadable": "",
            "LocationExpr": "",
            "DeclLine": 0
          },
          {
            "name": "key",
            "addr": 1374390329432,
            "onlyAddr": false,
            "type": "uintptr",
            "realType": "uintptr",
            "flags": 0,
            "kind": 7,
            "value": "0",
            "len": 0,
            "cap": 0,
            "children": [],
            "base": 0,
            "unreadable": "",
            "LocationExpr": "",
            "DeclLine": 0
          }
        ],
        "base": 0,
        "unreadable": "",
        "LocationExpr": "",
        "DeclLine": 0
      }
    ],
    "base": 1374390329344,
    "unreadable": "",
    "LocationExpr": "[block] DW_OP_fbreg -0x478 ",
    "DeclLine": 31
  },
  {
    "name": "v14",
    "addr": 1374390124704,
    "onlyAddr": false,
    "type": "interface {}",
    "realType": "interface {}",
    "flags": 1,
    "kind": 20,
    "value": "",
    "len": 0,
    "cap": 0,
    "children": [
      {
        "name": "data",
        "addr": 4302947088,
        "onlyAddr": false,
        "type": "int",
        "realType": "int",
        "flags": 0,
        "kind": 2,
        "value": "10",
        "len": 0,
        "cap": 0,
        "children": [],
        "base": 0,
        "unreadable": "",
        "LocationExpr": "",
        "DeclLine": 0
      }
    ],
    "base": 0,
    "unreadable": "",
    "LocationExpr": "[block] DW_OP_fbreg -0x18  (escaped)",
    "DeclLine": 37
  },
  {
    "name": "v15",
    "addr": 1374390184640,
    "onlyAddr": false,
    "type": "*int",
    "realType": "*int",
    "flags": 0,
    "kind": 22,
    "value": "1374390222888",
    "len": 1,
    "cap": 0,
    "children": [
      {
        "name": "",
        "addr": 1374390222888,
        "onlyAddr": false,
        "type": "int",
        "realType": "int",
        "flags": 0,
        "kind": 2,
        "value": "22",
        "len": 0,
        "cap": 0,
        "children": [],
        "base": 0,
        "unreadable": "",
        "LocationExpr": "",
        "DeclLine": 0
      }
    ],
    "base": 0,
    "unreadable": "",
    "LocationExpr": "[block] DW_OP_fbreg -0x480 ",
    "DeclLine": 38
  },
  {
    "name": "v16",
    "addr": 1374390184632,
    "onlyAddr": false,
    "type": "unsafe.Pointer",
    "realType": "unsafe.Pointer",
    "flags": 0,
    "kind": 26,
    "value": "1374390124704",
    "len": 1,
    "cap": 0,
    "children": [
      {
        "name": "",
        "addr": 1374390124704,
        "onlyAddr": false,
        "type": "void",
        "realType": "void",
        "flags": 0,
        "kind": 0,
        "value": "",
        "len": 0,
        "cap": 0,
        "children": [],
        "base": 0,
        "unreadable": "unknown or unsupported kind: \"invalid\"",
        "LocationExpr": "",
        "DeclLine": 0
      }
    ],
    "base": 0,
    "unreadable": "",
    "LocationExpr": "[block] DW_OP_fbreg -0x488 ",
    "DeclLine": 39
  }
]`)
